version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: docker:17.05.0-ce-git

    working_directory: ~/dark

    steps:
      - checkout
      - run: script/builder --compile
