version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install outer container utilities
          # coreutils for gnu date
          # bash for scripts
          command: |
            apk add --update bash coreutils


      # Setup for daily/weekly caches
      - run: date +"%F" > today-timestamp
      - run: date +"%F" -d "today - 1 days" > minus1-timestamp
      - run: date +"%F" -d "today - 2 days" > minus2-timestamp
      - run: date +"%F" -d "today - 3 days" > minus3-timestamp
      - run: date +"%F" -d "today - 4 days" > minus4-timestamp
      - run: date +"%F" -d "today - 5 days" > minus5-timestamp
      - run: date +"%F" -d "today - 6 days" > minus6-timestamp
      - run: date +"%F" -d "today - 7 days" > minus7-timestamp

      # main build
      - restore_cache:
          keys:
            - v1-build-{{ checksum "today-timestamp" }}
            - v1-build-{{ checksum "today - 1 days" }}
            - v1-build-{{ checksum "today - 2 days" }}
            - v1-build-{{ checksum "today - 3 days" }}
            - v1-build-{{ checksum "today - 4 days" }}
            - v1-build-{{ checksum "today - 5 days" }}
            - v1-build-{{ checksum "today - 6 days" }}
            - v1-build-{{ checksum "today - 7 days" }}

      # https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
      - run:
          name: Copy in app directory
          command: |
            docker create -v /home/dark/app --name vols alpine:3.4 /bin/true
            docker cp . vols:/home/dark/app
            # set the ownership of all this
            docker run -i --volumes-from vols dark sudo chown -R dark /home/dark/app

      - run: scripts/builder --compile --test

      - run:
          name: Copy out caches
          command: |
            docker cp vols:/home/dark/app/client/elm-stuff client/elm-stuff
            docker cp vols:/home/dark/app/client/tests/elm-stuff client/tests/elm-stuff
            docker cp vols:/home/dark/app/server/_build server/_build

      - save_cache:
          when: always
          paths:
            - client/elm-stuff
            - client/tests/elm-stuff
            - server/_build
          key: v1-build-{{ checksum "today-timestamp" }}



      - run:
          name: Run server
          background: true
          command: |
            scripts/builder --serve

      - run:
          name: Wait for server
          command: |
            while [[ "$(docker ps --last 1 --filter status=running --quiet)" == "" ]]; do
              printf '.'
              sleep 1
            done

      - run: scripts/run-in-docker integration-tests/run.sh

      - run:
          name: Copy out artifacts
          command: |
            docker cp dark:/home/dark/app/integration-tests/screenshots integration-tests/screenshots
            docker cp dark:/home/dark/app/logs logs

      - store_artifacts:
          path: integration-tests/screenshots

      - store_artifacts:
          path: logs

